// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.domain;

import com.guymoyo.domain.Choix;
import com.guymoyo.domain.ChoixDataOnDemand;
import com.guymoyo.domain.PanierDataOnDemand;
import com.guymoyo.domain.ParisDataOnDemand;
import com.guymoyo.service.ChoixService;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ChoixDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ChoixDataOnDemand: @Component;
    
    private Random ChoixDataOnDemand.rnd = new SecureRandom();
    
    private List<Choix> ChoixDataOnDemand.data;
    
    @Autowired
    private PanierDataOnDemand ChoixDataOnDemand.panierDataOnDemand;
    
    @Autowired
    private ParisDataOnDemand ChoixDataOnDemand.parisDataOnDemand;
    
    @Autowired
    ChoixService ChoixDataOnDemand.choixService;
    
    public Choix ChoixDataOnDemand.getNewTransientChoix(int index) {
        Choix obj = new Choix();
        setGain(obj, index);
        setMontantParis(obj, index);
        return obj;
    }
    
    public void ChoixDataOnDemand.setGain(Choix obj, int index) {
        BigDecimal gain = BigDecimal.valueOf(index);
        obj.setGain(gain);
    }
    
    public void ChoixDataOnDemand.setMontantParis(Choix obj, int index) {
        BigDecimal montantParis = BigDecimal.valueOf(index);
        obj.setMontantParis(montantParis);
    }
    
    public Choix ChoixDataOnDemand.getSpecificChoix(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Choix obj = data.get(index);
        Long id = obj.getId();
        return choixService.findChoix(id);
    }
    
    public Choix ChoixDataOnDemand.getRandomChoix() {
        init();
        Choix obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return choixService.findChoix(id);
    }
    
    public boolean ChoixDataOnDemand.modifyChoix(Choix obj) {
        return false;
    }
    
    public void ChoixDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = choixService.findChoixEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Choix' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Choix>();
        for (int i = 0; i < 10; i++) {
            Choix obj = getNewTransientChoix(i);
            try {
                choixService.saveChoix(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
