// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.domain;

import com.guymoyo.domain.League;
import com.guymoyo.domain.LeagueDataOnDemand;
import com.guymoyo.domain.UserAccountDataOnDemand;
import com.guymoyo.service.LeagueService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LeagueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LeagueDataOnDemand: @Component;
    
    private Random LeagueDataOnDemand.rnd = new SecureRandom();
    
    private List<League> LeagueDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand LeagueDataOnDemand.userAccountDataOnDemand;
    
    @Autowired
    LeagueService LeagueDataOnDemand.leagueService;
    
    public League LeagueDataOnDemand.getNewTransientLeague(int index) {
        League obj = new League();
        setDescription(obj, index);
        setImage(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void LeagueDataOnDemand.setDescription(League obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void LeagueDataOnDemand.setImage(League obj, int index) {
        byte[] image = String.valueOf(index).getBytes();
        obj.setImage(image);
    }
    
    public void LeagueDataOnDemand.setName(League obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public League LeagueDataOnDemand.getSpecificLeague(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        League obj = data.get(index);
        Long id = obj.getId();
        return leagueService.findLeague(id);
    }
    
    public League LeagueDataOnDemand.getRandomLeague() {
        init();
        League obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return leagueService.findLeague(id);
    }
    
    public boolean LeagueDataOnDemand.modifyLeague(League obj) {
        return false;
    }
    
    public void LeagueDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = leagueService.findLeagueEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'League' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<League>();
        for (int i = 0; i < 10; i++) {
            League obj = getNewTransientLeague(i);
            try {
                leagueService.saveLeague(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
