// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.domain;

import com.guymoyo.domain.Panier;
import com.guymoyo.domain.PanierDataOnDemand;
import com.guymoyo.domain.UserAccountDataOnDemand;
import com.guymoyo.service.PanierService;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PanierDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PanierDataOnDemand: @Component;
    
    private Random PanierDataOnDemand.rnd = new SecureRandom();
    
    private List<Panier> PanierDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand PanierDataOnDemand.userAccountDataOnDemand;
    
    @Autowired
    PanierService PanierDataOnDemand.panierService;
    
    public Panier PanierDataOnDemand.getNewTransientPanier(int index) {
        Panier obj = new Panier();
        setDateOfCreation(obj, index);
        setGainTotal(obj, index);
        setMontantTotal(obj, index);
        return obj;
    }
    
    public void PanierDataOnDemand.setDateOfCreation(Panier obj, int index) {
        Date dateOfCreation = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateOfCreation(dateOfCreation);
    }
    
    public void PanierDataOnDemand.setGainTotal(Panier obj, int index) {
        BigDecimal gainTotal = BigDecimal.valueOf(index);
        obj.setGainTotal(gainTotal);
    }
    
    public void PanierDataOnDemand.setMontantTotal(Panier obj, int index) {
        BigDecimal montantTotal = BigDecimal.valueOf(index);
        obj.setMontantTotal(montantTotal);
    }
    
    public Panier PanierDataOnDemand.getSpecificPanier(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Panier obj = data.get(index);
        Long id = obj.getId();
        return panierService.findPanier(id);
    }
    
    public Panier PanierDataOnDemand.getRandomPanier() {
        init();
        Panier obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return panierService.findPanier(id);
    }
    
    public boolean PanierDataOnDemand.modifyPanier(Panier obj) {
        return false;
    }
    
    public void PanierDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = panierService.findPanierEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Panier' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Panier>();
        for (int i = 0; i < 10; i++) {
            Panier obj = getNewTransientPanier(i);
            try {
                panierService.savePanier(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
