// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.domain;

import com.guymoyo.domain.Retrait;
import com.guymoyo.domain.RetraitDataOnDemand;
import com.guymoyo.domain.UserAccountDataOnDemand;
import com.guymoyo.service.RetraitService;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RetraitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RetraitDataOnDemand: @Component;
    
    private Random RetraitDataOnDemand.rnd = new SecureRandom();
    
    private List<Retrait> RetraitDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand RetraitDataOnDemand.userAccountDataOnDemand;
    
    @Autowired
    RetraitService RetraitDataOnDemand.retraitService;
    
    public Retrait RetraitDataOnDemand.getNewTransientRetrait(int index) {
        Retrait obj = new Retrait();
        setDateOfCreation(obj, index);
        setDescription(obj, index);
        setMontant(obj, index);
        return obj;
    }
    
    public void RetraitDataOnDemand.setDateOfCreation(Retrait obj, int index) {
        Date dateOfCreation = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateOfCreation(dateOfCreation);
    }
    
    public void RetraitDataOnDemand.setDescription(Retrait obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void RetraitDataOnDemand.setMontant(Retrait obj, int index) {
        BigDecimal montant = BigDecimal.valueOf(index);
        obj.setMontant(montant);
    }
    
    public Retrait RetraitDataOnDemand.getSpecificRetrait(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Retrait obj = data.get(index);
        Long id = obj.getId();
        return retraitService.findRetrait(id);
    }
    
    public Retrait RetraitDataOnDemand.getRandomRetrait() {
        init();
        Retrait obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return retraitService.findRetrait(id);
    }
    
    public boolean RetraitDataOnDemand.modifyRetrait(Retrait obj) {
        return false;
    }
    
    public void RetraitDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = retraitService.findRetraitEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Retrait' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Retrait>();
        for (int i = 0; i < 10; i++) {
            Retrait obj = getNewTransientRetrait(i);
            try {
                retraitService.saveRetrait(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
