// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.domain;

import com.guymoyo.domain.Deposit;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Deposit_Roo_Configurable {
    
    declare @type: Deposit: @Configurable;
    
}
