// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web.converter;

import com.guymoyo.web.converter.SportTypeConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SportTypeConverter_Roo_Configurable {
    
    declare @type: SportTypeConverter: @Configurable;
    
}
