// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.ChoixBean;
import java.io.Serializable;

privileged aspect ChoixBean_Roo_Serializable {
    
    declare parents: ChoixBean implements Serializable;
    
    private static final long ChoixBean.serialVersionUID = 1L;
    
}
