// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.EquipBean;
import java.io.Serializable;

privileged aspect EquipBean_Roo_Serializable {
    
    declare parents: EquipBean implements Serializable;
    
    private static final long EquipBean.serialVersionUID = 1L;
    
}
