// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.LeagueBean;
import java.io.Serializable;

privileged aspect LeagueBean_Roo_Serializable {
    
    declare parents: LeagueBean implements Serializable;
    
    private static final long LeagueBean.serialVersionUID = 1L;
    
}
