// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.PanierBean;
import java.io.Serializable;

privileged aspect PanierBean_Roo_Serializable {
    
    declare parents: PanierBean implements Serializable;
    
    private static final long PanierBean.serialVersionUID = 1L;
    
}
