// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.RetraitBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RetraitBean_Roo_Configurable {
    
    declare @type: RetraitBean: @Configurable;
    
}
