// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.RetraitBean;
import java.io.Serializable;

privileged aspect RetraitBean_Roo_Serializable {
    
    declare parents: RetraitBean implements Serializable;
    
    private static final long RetraitBean.serialVersionUID = 1L;
    
}
