// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.SportTypeBean;
import java.io.Serializable;

privileged aspect SportTypeBean_Roo_Serializable {
    
    declare parents: SportTypeBean implements Serializable;
    
    private static final long SportTypeBean.serialVersionUID = 1L;
    
}
