// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.web;

import com.guymoyo.web.UserAccountBean;
import java.io.Serializable;

privileged aspect UserAccountBean_Roo_Serializable {
    
    declare parents: UserAccountBean implements Serializable;
    
    private static final long UserAccountBean.serialVersionUID = 1L;
    
}
